# _config.yml
# Site configuration

title: Weiwei-Geo
description: "Life is a tree full of possibilities"
baseurl: ""
url: "https://weiwei-geo.github.io"

# Custom settings
avatar: "/assets/images/avatar.jpg"
toc: true

# Markdown settings
markdown: kramdown
highlighter: rouge
permalink: /posts/:year/:month/:day/:title/

# GitHub Pages plugins
plugins:
  - jekyll-feed
  - jekyll-seo-tag

# Defaults
defaults:
  - scope:
      path: ""
      type: "posts"
    values:
      layout: post
      author: weiwei
